import 'package:flutter/material.dart';
import '../services/auth_service.dart';
import 'home_screen.dart';

class TermsOfServicePage extends StatelessWidget {
  final bool showButtons;
  const TermsOfServicePage({super.key, this.showButtons = true});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        title: const Text(
          'Terms of Service',
          style: TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
        ),
        backgroundColor: Colors.white,
        elevation: 0,
        automaticallyImplyLeading: !showButtons, // Enable back button if viewing from drawer
        leading: !showButtons
            ? IconButton(
                icon: const Icon(Icons.arrow_back_ios, color: Colors.black),
                onPressed: () => Navigator.pop(context),
              )
            : null,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: const [
                      Text(
                        '1. Acceptance of Terms',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                      ),
                      SizedBox(height: 5),
                      Text(
                        'By accessing or using the AgriScan mobile application, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our application.',
                      ),
                      SizedBox(height: 15),
                      Text(
                        '2. Description of Service',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                      ),
                      SizedBox(height: 5),
                      Text(
                        'AgriScan provides AI-powered palay disease diagnosis, community features, and agricultural information.',
                      ),
                      SizedBox(height: 15),
                      Text(
                        'IMPORTANT DISCLAIMER:',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.red),
                      ),
                      SizedBox(height: 5),
                      Text(
                        'The diagnosis results provided by AgriScan are generated by Artificial Intelligence and are for informational purposes only. They should not be considered as professional agricultural advice. We recommend consulting with a professional agronomist or local agricultural extension office for confirmation and treatment.',
                      ),
                      SizedBox(height: 15),
                      Text(
                        '3. Limitation of Liability',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                      ),
                      SizedBox(height: 5),
                      Text(
                        'AgriScan Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of crops, profits, or data, arising out of or in connection with your use of the service or reliance on any diagnosis results.',
                      ),
                      SizedBox(height: 15),
                      Text(
                        '4. Changes to Terms',
                        style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                      ),
                      SizedBox(height: 5),
                      Text(
                        'We reserve the right to modify these terms at any time. We will notify users of any significant changes. Your continued use of the app after such changes constitutes your acceptance of the new terms.',
                      ),
                    ],
                  ),
                ),
              ),
              if (showButtons) ...[
                const SizedBox(height: 20),
                Row(
                  children: [
                    Expanded(
                      child: OutlinedButton(
                        onPressed: () async {
                          // Decline TOS logs them out
                          await AuthService().logout();
                        },
                        style: OutlinedButton.styleFrom(
                          padding: const EdgeInsets.symmetric(vertical: 15),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                        child: const Text('Decline', style: TextStyle(color: Colors.red)),
                      ),
                    ),
                    const SizedBox(width: 20),
                    Expanded(
                      child: ElevatedButton(
                        onPressed: () async {
                          // Accept TOS saves preference and navigates to welcome screen
                          await AuthService().acceptTermsOfService();
                          if (context.mounted) {
                            Navigator.pushReplacement(
                              context,
                              MaterialPageRoute(
                                builder: (context) => const HomeScreen(),
                              ),
                            );
                          }
                        },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.green,
                          padding: const EdgeInsets.symmetric(vertical: 15),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                        child: const Text('Accept', style: TextStyle(color: Colors.white)),
                      ),
                    ),
                  ],
                ),
              ],
            ],
          ),
        ),
      ),
    );
  }
}
