// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkWqpS0otFXYpXi36uOP5vLcNcsURRyGs',
    appId: '1:689755860519:android:969256f3b5aae37fe4a802',
    messagingSenderId: '689755860519',
    projectId: 'capstoneloginsign-4b735',
    databaseURL: 'https://capstoneloginsign-4b735-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstoneloginsign-4b735.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLe6byb1tqla_2Zp-bcuwQaEIOL7eKii4',
    appId: '1:689755860519:web:4634ff6fa3f3e37ae4a802',
    messagingSenderId: '689755860519',
    projectId: 'capstoneloginsign-4b735',
    authDomain: 'capstoneloginsign-4b735.firebaseapp.com',
    databaseURL: 'https://capstoneloginsign-4b735-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstoneloginsign-4b735.firebasestorage.app',
    measurementId: 'G-QRKLGFSJKD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHqJj0KPqp-_AoRU5RM87689RX5BmGpIY',
    appId: '1:689755860519:ios:579a25ed02d5230be4a802',
    messagingSenderId: '689755860519',
    projectId: 'capstoneloginsign-4b735',
    databaseURL: 'https://capstoneloginsign-4b735-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstoneloginsign-4b735.firebasestorage.app',
    iosBundleId: 'com.example.myCapstoneApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHqJj0KPqp-_AoRU5RM87689RX5BmGpIY',
    appId: '1:689755860519:ios:579a25ed02d5230be4a802',
    messagingSenderId: '689755860519',
    projectId: 'capstoneloginsign-4b735',
    databaseURL: 'https://capstoneloginsign-4b735-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstoneloginsign-4b735.firebasestorage.app',
    iosBundleId: 'com.example.myCapstoneApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6dvCRvsJi5_Wh9IC9c5olOo3RPDTl6A8',
    appId: '1:689755860519:web:9d5abb8eb768518ee4a802',
    messagingSenderId: '689755860519',
    projectId: 'capstoneloginsign-4b735',
    authDomain: 'capstoneloginsign-4b735.firebaseapp.com',
    databaseURL: 'https://capstoneloginsign-4b735-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'capstoneloginsign-4b735.firebasestorage.app',
    measurementId: 'G-F7HFFHQCSM',
  );

}